### PR TITLE
back to SLASHSTAR_STYLE settings (lost somewhere)

### PR DESCRIPTION
**Pull request by witokondoria**

### CODE REVIEW

**Comment by witokondoria** [comment]
Will fix Stratio/cassandra-lucene-index#166

**Comment by antonioalf** [comment]
:shipit:

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/Stratio%20parent/159/)

**Pull request merged**
